# Normalization Problem


In [1]:
import numpy as np


In [2]:
x = np.random.random((5,5))
print (x)

[[0.51669987 0.60856124 0.3162921  0.54046794 0.84956104]
 [0.82811427 0.13971513 0.83021087 0.68584075 0.71941128]
 [0.61976069 0.79893866 0.60530939 0.51920135 0.50858937]
 [0.81881982 0.69206366 0.41201376 0.43931211 0.18865444]
 [0.93910584 0.97766578 0.80586227 0.63212884 0.61722132]]


In [3]:
xmean = np.mean(x)
xstd = np.std(x)
z = (x-xmean/xstd)
print(z)

[[-2.43332279 -2.34146141 -2.63373055 -2.40955471 -2.10046162]
 [-2.12190838 -2.81030752 -2.11981178 -2.2641819  -2.23061138]
 [-2.33026196 -2.15108399 -2.34471326 -2.4308213  -2.44143329]
 [-2.13120283 -2.25795899 -2.53800889 -2.51071055 -2.76136821]
 [-2.01091682 -1.97235687 -2.14416039 -2.31789381 -2.33280133]]


# Divisible by 3 Problem


In [4]:
array = np.arange(1, 101)
print(array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [5]:
x = array ** 2
d3 = x.reshape(10, 10)
print(d3)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [6]:
div3 = x[x%3==0]
print(div3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
